app:
    resource: "@AppBundle/Controller/"
    type:     annotation
index:
    pattern:  /
    defaults: { _controller: AlterdBundle:Screen:gameScreen }
create_user:
    pattern:  /api/users/create
    defaults: { _controller: AlterdBundle:Api/Users:createUser}
login_user:
    pattern:  /api/users/login
    defaults: { _controller: AlterdBundle:Api/Users:loginUser}